version: '2.0'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: npm-register
    restart: always
    environment:
      - VERDACCIO_PORT=80
    ports:
      - '4873:80'
    volumes:
      - /srv/verdaccio/conf:/verdaccio/conf
      - /srv/verdaccio/storage:/verdaccio/storage
      - /srv/verdaccio/plugins:/verdaccio/plugins
