version: '2.0'
services:
  drone:
    image: drone/drone:1
    container_name: drone_server
    restart: always
    environment:
      DRONE_GITEA_SERVER: 'http://82.157.55.94:8929'
      DRONE_GITEA_CLIENT_ID: '3601a547-effd-46de-967d-8ea0e4a9b2b1'
      DRONE_GITEA_CLIENT_SECRET: 'yFWXdRjFDEPsnrhvW1jtSGdkcIkKs4EJn6h8LP98hqU5'
      DRONE_RUNNER_CAPACITY: 2
      DRONE_SERVER_HOST: 'drone.mwjz.live'
      DRONE_SERVER_PROTO: 'https'
      DRONE_RPC_SECRET: 'e1ad8a7f3dbc68ca9c21bcc949335009'
      DRONE_USER_CREAT: 'username:yxs970707,admin:true'
    ports:
      - '7929:80'
    # networks:
    #   drone-net:
    #     aliases:
    #       - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/drone:/var/lib/drone

  ssh-runner:
    image: drone/drone-runner-ssh
    container_name: drone-ssh-runner
    restart: always
    environment:
      DRONE_RUNNER_NAME: 'drone-ssh-runner'
      DRONE_RPC_HOST: '10.0.24.12:7929'
      DRONE_RPC_PROTO: 'http'
      DRONE_RUNNER_CAPACITY: 2
      DRONE_SERVER_PROTO: 'https'
      DRONE_RPC_SECRET: 'e1ad8a7f3dbc68ca9c21bcc949335009'
    ports:
      - 7931:3000
    depends_on:
      - drone
    # networks:
    #   drone-net:
    #     aliases:
    #       - drone-ssh-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  runner:
    image: drone/drone-runner-docker:1
    container_name: drone_runner
    restart: always
    environment:
      DRONE_RUNNER_NAME: 'drone-runner'
      DRONE_RPC_HOST: '10.0.24.12:7929'
      DRONE_RUNNER_CAPACITY: 2
      DRONE_SERVER_HOST: '10.0.24.12:7930'
      DRONE_SERVER_PROTO: 'https'
      DRONE_RPC_SECRET: 'e1ad8a7f3dbc68ca9c21bcc949335009'
      DRONE_UI_USERNAME: 'yxs970707'
      DRONE_UI_PASSWORD: 'yxs970707'
    ports:
      - '7930:3000'
    depends_on:
      - drone
    # networks:
    #   drone-net:
    #     aliases:
    #       - drone-runner
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
# networks:
#   drone-net:
#     external: true # 使用外部网络, 需先创建网络
