version: '2.0'
services:
  server:
    image: drone/drone:2
    container_name: drone_server
    restart: always
    environment:
      DRONE_GITEA_SERVER: http://82.157.55.94:8929
      DRONE_GITEA_CLIENT_ID: 'b3ab48b3-ee2d-4d1e-999e-2ec62c41972b'
      DRONE_GITEA_CLIENT_SECRET: 'PECCuWdoJU9g9wKFJ0X9Mvv75y0f1T3eMb3Gu0VyDEyi'
      DRONE_SERVER_HOST: '82.157.55.94:7929'
      DRONE_SERVER_PROTO: 'http'
      DRONE_RPC_SECRET: 'e1ad8a7f3dbc68ca9c21bcc949335009'
    ports:
      - '7929:80'
    volumes:
      - /srv/drone:/var/lib/drone
  runner:
    image: drone/drone-runner-docker:1
    container_name: drone_runner
    restart: always
    environment:
      DRONE_RUNNER_NAME: 'my-first-runner'
      DRONE_RPC_HOST: '10.0.24.12:7929'
      DRONE_RUNNER_CAPACITY: 2
      DRONE_SERVER_HOST: '82.157.55.94:7930'
      DRONE_SERVER_PROTO: 'http'
      DRONE_RPC_SECRET: 'e1ad8a7f3dbc68ca9c21bcc949335009'
      DRONE_UI_USERNAME: 'yxs70707'
      DRONE_UI_PASSWORD: 'yxs70707'
    ports:
      - '7930:3000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
