version: '2.0'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: yxs970707
      MYSQL_USER: yan
      MYSQL_PASSWORD: yan      
    ports:
      - "3306:3306"
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
    volumes:
      - /srv/mysql/data:/var/lib/mysql
      - /srv/mysql/config/my.cnf:/etc/mysql/my.cnf
      - /srv/mysql/log:/var/log/mysql
