version: '2.0' #版本号
services:
  nginx:
    restart: always
    image: daocloud.io/library/nginx:latest
    container_name: home #容器名
    ports:
      - 80:80 #启动端口
      - 443:443
    volumes: #数据卷映射地址
      - /srv/home/conf.d:/etc/nginx/conf.d
      - /srv/home/nginx.conf:/etc/nginx/nginx.conf
      - /srv/home/logs:/var/log/nginx
      - /srv/home/html:/usr/share/nginx/html
